#! /usr/bin/env Rscript
## This runs testme test script inst/testme/test-all.equal.connection.R
## Don't edit - it was autogenerated by inst/testme/deploy.R
parallelly:::testme("all.equal.connection")
