#! /usr/bin/env Rscript
## This runs testme test script inst/testme/test-registerClusterTypes.R
## Don't edit - it was autogenerated by inst/testme/deploy.R
parallelly:::testme("registerClusterTypes")
