## This runs 'testme' test inst/testme/test-<name>.R scripts
## Don't edit - it was autogenerated by inst/testme/deploy.R
testme <- function(name) {
  Sys.setenv(R_TESTME_PACKAGE = 'parallelly')
  Sys.setenv(R_TESTME_NAME = name)
  on.exit(Sys.unsetenv('R_TESTME_NAME'))
  source(system.file(package = 'parallelly', 'testme', 'run.R', mustWork = TRUE))
}
